/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthCard: typeof import('./components/AuthCard.vue')['default']
    CartDrawer: typeof import('./components/CartDrawer.vue')['default']
    ProductForm: typeof import('./components/ProductForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StorePreview: typeof import('./components/StorePreview.vue')['default']
  }
}
